name: Deploy Full Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ================= FRONTEND =================
      - name: Install & Build Frontend
        run: |
          cd frontEnd
          npm install
          npm run build

      - name: Upload Frontend to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.CPANEL_HOST }}
          username: ${{secrets.CPANEL_USER }}
          key: ${{secrets.CPANEL_PASSWORD}}
          port: ${{secrets.CPANEL_PORT }}
          source: "frontEnd/dist/*"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/"

      # ================= BACKEND =================
      - name: Upload Backend to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_PASSWORD }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "backend/*"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/server/"

      - name: Install Backend & Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/${{ secrets.CPANEL_USER }}/public_html/server
            npm install
            pm2 restart 0