name: Deploy Full Project (Frontend + Backend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Install Frontend Dependencies
        working-directory: frontEnd
        run: npm ci

      - name: Build Frontend (Inject Production Env)
        working-directory: frontend
        env:
          VITE_APP_SERVER_PATH: ${{ secrets.VITE_APP_SERVER_PATH }}
        run: npm run build

      # ================= DEPLOY FRONTEND DIST =================
      - name: Upload Frontend dist to public_html
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "frontEnd/dist/**"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/"
          overwrite: true

      # ================= DEPLOY BACKEND CODE =================
      - name: Upload Backend to cPanel (server folder)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "backend/**"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/server/"
          overwrite: true

      # ================= INSTALL & RESTART BACKEND =================
      - name: Install Backend & Restart PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/${{ secrets.CPANEL_USER }}/public_html/server
            npm install --omit=dev
            pm2 restart 0
            pm2 save