name: Deploy Full Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ================= CHECKOUT =================
      - name: Checkout Code
        uses: actions/checkout@v3

      # ================= FRONTEND =================
      - name: Install & Build Frontend
        run: |
          cd frontEnd
          npm install
          npm run build

      - name: Upload Frontend to cPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "frontEnd/dist/*"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/"
          overwrite: true

      # ================= BACKEND =================
      - name: Upload Backend to cPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "backend/*"
          target: "/home/${{ secrets.CPANEL_USER }}/public_html/server/"
          overwrite: true

      # ================= INSTALL & RESTART =================
      - name: Install Backend & Restart Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/${{ secrets.CPANEL_USER }}/public_html/server
            npm install
            pm2 restart 0 || pm2 start index.js --name server